### ISSUE TITLE
RuntimeError in demo: xgeom not 3-vector

### ISSUE THREAD

**Issue by a-larkins99** [pace-neutrons/pace-python-demo#2]
When running the final block in demo.ipynb, the following error occurs:
```
RuntimeError                              Traceback (most recent call last)
Cell In[15], line 7
      5 shape = 'cuboid';
      6 shape_pars = [0.01,0.05,0.01];
----> 7 wsc = m.set_sample(wsc, m.IX_sample(is_crystal, xgeom, ygeom, shape, shape_pars));
      8 ei = 40; freq = 400; chopper = 'g';
      9 wsc = m.set_instrument(wsc, m.merlin_instrument(ei, freq, chopper));

File ~\AppData\Local\mambaforge\envs\pacepython_test\Lib\site-packages\libpymcr\Matlab.py:72, in NamespaceWrapper.__call__(self, *args, **kwargs)
     70 args += sum(kwargs.items(), ())
     71 args = unwrap(args, self._interface)
---> 72 return wrap(self._interface.call(self._name, *args, nargout=nargout), self._interface)

RuntimeError: MatlabExecutionError: 
  File "C:\Users\oms84157\AppData\Local\Temp\oms84157\mcrCache9.14\pace_R2\Users\oms84157\Documents\pace-python\build\temp.win-amd64-cpython-311\Release\CTF\Herbert\classes\instrument_classes\instrument\@IX_sample\IX_sample.m", line 178, function "IX_sample.set.xgeom_"
  File "C:\Users\oms84157\AppData\Local\Temp\oms84157\mcrCache9.14\pace_R2\Users\oms84157\Documents\pace-python\build\temp.win-amd64-cpython-311\Release\CTF\Herbert\classes\instrument_classes\instrument\@IX_sample\IX_sample.m", line 121, function "IX_sample.IX_sample"
  File "C:\Users\oms84157\AppData\Local\Temp\oms84157\mcrCache9.14\pace_R2\Users\oms84157\Documents\pace-python\src\call.m", line 31, function "call"

: 'xgeom' must be a three-vector
```

**Comment by mducle** [comment]
@a-larkins99 Sorry the syntax in Horace changed from when I wrote this, the line now needs to be:

<strike>

```
wsc = m.set_sample(wsc, m.IX_sample(xgeom, ygeom, shape, shape_pars, single_crystal=is_crystal));
```

</strike>

You can also remove all the semi-colons but they don't really cause any problems...

Edit: Actually the syntax doesn't seem to match the [documentation](https://github.com/pace-neutrons/Horace/blob/master/herbert_core/classes/instrument_classes/instrument/%40IX_sample/IX_sample.m#L44) and the above code doesn't work. Removing the `is_crystal` works... and the thing is suppose to have `single_crystal=True` by default in any case.

```
wsc = m.set_sample(wsc, m.IX_sample(xgeom, ygeom, shape, shape_pars));
```
